# GitLab CI

stages:
    - build_dev
    - push_dev
  
variables:
    REGISTRY_GROUP_PROJECT: $CI_REGISTRY/4sconsult/box4s

before_script:
    - cp /home/amadmin/box4s/docker/suricata/.env docker/suricata/.env
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build_dev:
    stage: build_dev
    script:
        - docker-compose -f docker/box4security.yml build

push_dev:
    stage: push_dev
    script:
        - docker-compose -f docker/box4security.yml push

  
  