"""Add Wizard State

Revision ID: 031dd699edaa
Revises: d995a93c3a9c
Create Date: 2020-11-04 10:34:08.622945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from source.wizard.models import WizardState, WizardStateNames
# revision identifiers, used by Alembic.
revision = '031dd699edaa'
down_revision = 'd995a93c3a9c'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade to migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'wizardstatenames',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'wizardstate',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('state_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['state_id'], ['wizardstatenames.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(WizardStateNames.__table__, [
        {'id': 1, 'name': 'Force Disable'},
        {'id': 2, 'name': 'Enabled'},
        {'id': 3, 'name': 'Completed'},
    ])
    op.bulk_insert(WizardState.__table__, [
        {'state_id': 2},
    ])
    # ### end Alembic commands ###


def downgrade():
    """Downgrade to migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wizardstate')
    op.drop_table('wizardstatenames')
    # ### end Alembic commands ###
