"""empty message

Revision ID: 045ed1db87f6
Revises: 56e9b3f51ec8
Create Date: 2020-04-22 07:57:41.568929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '045ed1db87f6'
down_revision = '56e9b3f51ec8'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade to migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('description', sa.String(length=255), nullable=True))


def downgrade():
    """Downgrade to migration."""
    op.drop_column('role', 'description')
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
