"""empty message

Revision ID: 045ed1db87f6
Revises: 56e9b3f51ec8
Create Date: 2020-04-22 07:57:41.568929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '045ed1db87f6'
down_revision = '56e9b3f51ec8'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade to migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert('role',
                   [
                       {'id': 1, 'name': 'Super Admin', 'description': 'Super Admin'},
                       {'id': 2, 'name': 'Filter', 'description': 'Sehen und Anlegen von Filtern'},
                       {'id': 3, 'name': 'Updates', 'description': 'Starten von Updates'},
                       {'id': 4, 'name': 'User-Management', 'description': 'Bearbeiten und Anlegen von Benutzern'},
                       {'id': 5, 'name': 'FAQ', 'description': 'Ansicht FAQ und Benutzung 4sConsult Kontaktformular'},
                       {'id': 6, 'name': 'Dashboards-Master', 'description': 'Freigabe für alle Dashboards'},
                       {'id': 7, 'name': 'SIEM', 'description': 'Freigabe für SIEM-Dashboards'},
                       {'id': 8, 'name': 'Schwachstellen', 'description': 'Freigabe für Schwachstellen-Dashboards'},
                       {'id': 9, 'name': 'Netzwerk', 'description': 'Freigabe für Netzwerk-Dashboards'},
                   ])
    # ### end Alembic commands ###


def downgrade():
    """Downgrade to migration."""
    op.execute('DELETE FROM "role" WHERE id<10')
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
