"""empty message

Revision ID: 1d03ea9e33bd
Revises: 2bcd96b138e4
Create Date: 2020-04-23 13:20:52.008628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from source.models import Role

# revision identifiers, used by Alembic.
revision = '1d03ea9e33bd'
down_revision = '2bcd96b138e4'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade to migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(Role.__table__,
                   [
                       {'id': 10, 'name': 'Startseite', 'description': 'Freigabe für die Startseite'},
                   ])
    # ### end Alembic commands ###


def downgrade():
    """Downgrade to migration."""
    op.execute('DELETE FROM "role" WHERE id=10')
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
