"""network and types

Revision ID: 5aadb38f6936
Revises: 96cfbddbc495
Create Date: 2020-10-21 08:27:58.262814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5aadb38f6936'
down_revision = '96cfbddbc495'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade to migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'networktype',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'scancategory',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'network',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('ip_address', sa.String(length=24), nullable=False),
        sa.Column('cidr', sa.Integer(), nullable=False),
        sa.Column('vlan', sa.String(length=50), nullable=True),
        sa.Column('scancategory_id', sa.Integer(), nullable=True),
        sa.Column('scan_weekday', sa.String(length=24), nullable=True),
        sa.Column('scan_time', sa.Time(), nullable=True),
        sa.ForeignKeyConstraint(['scancategory_id'], ['scancategory.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'network_networktype',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('network_id', sa.Integer(), nullable=True),
        sa.Column('networktype_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['network_id'], ['network.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['networktype_id'], ['networktype.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    """Downgrade to migration."""
    op.drop_table('network_networktype')
    op.drop_table('network')
    op.drop_table('scancategory')
    op.drop_table('networktype')
