# ======================== Elasticsearch Configuration =========================
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
# ---------------------------------- Cluster -----------------------------------
cluster.name: box4scluster
# ------------------------------------ Node ------------------------------------
node.name: box4security
# ----------------------------------- Paths ------------------------------------
path.data: /data/elasticsearch
path.logs: /var/log/elasticsearch
# Snapshot Repo
path.repo: /data/elasticsearch_backup/Snapshots
# ----------------------------------- Memory -----------------------------------
# ---------------------------------- Network -----------------------------------
network.host: 0.0.0.0
discovery.type: single-node
# --------------------------------- Discovery ----------------------------------
discovery.zen.ping.unicast.hosts: ["localhost"]
discovery.zen.minimum_master_nodes: 1
# ---------------------------------- Gateway -----------------------------------
gateway.recover_after_nodes: 1
# ---------------------------------- Various -----------------------------------
xpack.ml.enabled: false
xpack.security.enabled: false
xpack.security.transport.ssl.enabled: false
