version: "2.3"
services:
    wazuh:
        container_name: wazuh
        image: "registry.gitlab.com/4sconsult/box4s/wazuh:1.8.7"
        build: .
        hostname: wazuh-manager
        restart: always
        ports:
        - "1514:1514/udp"
        - "1515:1515"
        - "514:514/udp"
        - "55000:55000"
        volumes:
        - /var/lib/box4s/wazuh-authd.pass:/wazuh-config-mount/etc/authd.pass
        env_file:
        - /home/amadmin/box4s/config/secrets/wazuh.conf
        - /etc/box4s/modules.conf