wazuh:
    container_name: wazuh
    image: "registry.gitlab.com/4sconsult/box4s/wazuh:dev"
    build: .
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    env_file:
      - ../../config/secrets/wazuh.conf
      - /etc/box4s/modules.conf