version: '2.3'

services:
  elasticsearch:
    build: elasticsearch/.
    container_name: elasticsearch
    restart: always
    ports:
     - 9200:9200
    image: "registry.gitlab.com/4sconsult/box4s/elasticsearch:dev"
    volumes:
     - data:/data
    env_file:
      - elasticsearch/.env.es
  kibana:
    build: kibana/.
    container_name: kibana
    restart: always
    environment:
     - INT_IP=${INT_IP}
    env_file:
     - ../config/secrets/wazuh.conf
    ports:
     - 127.0.0.1:5601:5601
    image: "registry.gitlab.com/4sconsult/box4s/kibana:dev"
    depends_on:
      elasticsearch:
        condition: service_healthy
    stop_signal: SIGKILL
  openvas:
    build: openvas
    container_name: openvas
    restart: always
    environment:
      - INT_IP=${INT_IP}
    ports:
      - 9392:9392
    volumes:
      - varlib_openvas:/var/lib/openvas
      - varlib_logstash:/var/lib/logstash
    image: "registry.gitlab.com/4sconsult/box4s/openvas:dev"
    env_file:
      - ../config/secrets/openvas.conf
  suricata:
    build: suricata/.
    container_name: suricata
    restart: always
    image: "registry.gitlab.com/4sconsult/box4s/suricata:dev"
    network_mode: "host"
    env_file:
      - suricata/.env
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - data:/data
      - varlib_suricata:/var/lib/suricata/
      - varlib_box4s:/var/lib/box4s/
  metricbeat:
    build: metricbeat/.
    container_name: metricbeat
    image: "registry.gitlab.com/4sconsult/box4s/metricbeat:dev"
    depends_on:
      elasticsearch:
        condition: service_healthy
  heartbeat:
    build: heartbeat/.
    container_name: heartbeat
    image: "registry.gitlab.com/4sconsult/box4s/heartbeat:dev"
    depends_on:
      elasticsearch:
        condition: service_healthy
  logstash:
    build: logstash/.
    container_name: logstash
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file:
     - /etc/default/logstash
     - ../config/secrets/db.conf
     - logstash/.env.ls
    ports:
      - 9600:9600
      - 5044:5044
      - 5046:5046
    image: "registry.gitlab.com/4sconsult/box4s/logstash:dev"
    volumes:
      - varlib_logstash:/var/lib/logstash/
      - etcbox4s_logstash:/etc/logstash/conf.d/general/
      - varlib_box4s:/var/lib/box4s/
  filebeat:
    build: filebeat/.
    container_name: filebeat
    depends_on:
      logstash:
        condition: service_healthy
    image: "registry.gitlab.com/4sconsult/box4s/filebeat:dev"
    volumes:
      - varlib_logstash:/var/lib/logstash/
      - data:/data
  web:
    container_name: web
    networks:
      default:
        ipv4_address: 172.20.08.11
    image: "registry.gitlab.com/4sconsult/box4s/web:dev"
    build: web/.
    command: >
     bash -c "python main.py db upgrade head &&
     gunicorn --bind 0.0.0.0:5000 main:app"
    volumes:
       - static_volume:/home/app/web/source/static
       - /var/log/box4s/:/var/log/box4s/
       - varlib_box4s/:/var/lib/box4s/
       - varlib_elastalert_rules:/var/lib/elastalert/rules/
       - /etc/box4s/smtp.conf:/etc/box4s/smtp.conf
       - /etc/box4s/modules.conf:/etc/box4s/modules.conf
       - /etc/msmtprc:/etc/box4s/msmtprc
       - /etc/ssl/certs/BOX4s-SMTP.pem:/etc/ssl/certs/BOX4s-SMTP.pem
       - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    expose:
      - 5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/_health"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Add dockerhost IP to /etc/hosts in container for ssh
    extra_hosts:
      - "dockerhost:${INT_IP}"
    env_file:
      - web/web.env
      - ../config/secrets/web.conf
      - /etc/box4s/smtp.conf
      - /etc/box4s/modules.conf
      - ../VERSION
    environment:
      - KUNDE
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: "registry.gitlab.com/4sconsult/box4s/db:dev"
    build: db/.
    volumes:
      - varlib_postgresql/:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ../config/secrets/db.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    container_name: nginx
    image: "registry.gitlab.com/4sconsult/box4s/nginx:dev"
    build: nginx/.
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/source/static
      # certs (placed in host /etc/ folder by install script)
      - /etc/nginx/certs:/etc/nginx/certs
    depends_on:
      - web
      - kibana
      - wiki

  dnsmasq:
    container_name: dnsmasq
    image: "registry.gitlab.com/4sconsult/box4s/dnsmasq:dev"
    build: dnsmasq/.
    ports:
      - 53:5353/tcp
      - 53:5353/udp
    volumes:
      - varlib_box4s:/var/lib/box4s/
  elastalert:
    container_name: elastalert
    image: "registry.gitlab.com/4sconsult/box4s/elastalert:dev"
    depends_on:
      elasticsearch:
        condition: service_healthy
    build: elastalert/.
    restart: always
    volumes:
      - varlib_elastalert_rules:/opt/elastalert/rules
    expose:
      - 3030
      - 3333
  wiki:
    container_name: wiki
    image: "registry.gitlab.com/4sconsult/box4s/wiki:dev"
    build: wiki/.
    restart: always
    volumes:
      - varlib_docs:/wiki/
    expose:
      - 80
  core4s:
    container_name: core4s
    build: core4s/.
    restart: always
    env_file:
     - ../config/secrets/db.conf
     - ../config/secrets/secrets.conf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /data/suricata/eve.json:/core4s/workfolder/suricata/eve.json
      - /var/lib/box4s/IP2LOCATION-LITE-DB5.IPV6.BIN:/core4s/workfolder/var/lib/box4s/IP2LOCATION-LITE-DB5.IPV6.BIN
      - /var/lib/box4s/IP2LOCATION-LITE-DB5.BIN:/core4s/workfolder/var/lib/box4s/IP2LOCATION-LITE-DB5.BIN
      #- /home/amadmin/box4s/config/secrets:/core4s/secrets
    #image: "registry.gitlab.com/4sconsult/box4s/core4s:dev"
networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.08.0/24
volumes:
  # to persist data beyond container's life
  static_volume:
  data:
    external: true
  varlib_postgresql:
    external: true
  varlib_box4s:
    external: true
  varlib_logstash:
    external: true
  varlib_suricata:
    external: true
  varlib_openvas:
    external: true
  varlib_docs:
    external: true
  varlib_elastalert_rules:
    external: true
  etcbox4s_logstash:
    external: true
