version: '2.3'

services:
  elasticsearch:
    build: elasticsearch/.
    container_name: elasticsearch
    restart: always
    ports:
     - 127.0.0.1:9200:9200
    image: "registry.gitlab.com/4sconsult/box4s/elasticsearch:1.8.10-rc"
    volumes:
     - /data/elasticsearch:/data/elasticsearch
     - /data/elasticsearch_backup:/data/elasticsearch_backup
    env_file:
      - elasticsearch/.env.es
  kibana:
    build: kibana/.
    container_name: kibana
    restart: always
    environment:
     - INT_IP=${INT_IP}
    env_file:
     - ../config/secrets/wazuh.conf
    ports:
     - 127.0.0.1:5601:5601
    image: "registry.gitlab.com/4sconsult/box4s/kibana:1.8.10-rc"
    depends_on:
      elasticsearch:
        condition: service_healthy
    stop_signal: SIGKILL
    user: "1000:44269"
  spiderfoot:
    build: spiderfoot
    container_name: spiderfoot
    restart: always
    volumes:
        - spiderfoot_data:/var/lib/spiderfoot
    ports:
        - 5001:8080
    user: "2000:44269"
    image: "registry.gitlab.com/4sconsult/box4s/spiderfoot:1.8.10-rc"
  openvas:
    build: openvas
    container_name: openvas
    restart: always
    environment:
      - INT_IP=${INT_IP}
    ports:
      - 127.0.0.1:9392:9392
    expose:
      - 9390
    volumes:
      - gvm-data:/data
      - varlib_logstash:/var/lib/logstash
    image: "registry.gitlab.com/4sconsult/box4s/openvas:1.8.10-rc"
    env_file:
      - ../config/secrets/openvas.conf
  suricata:
    build: suricata/.
    container_name: suricata
    restart: always
    image: "registry.gitlab.com/4sconsult/box4s/suricata:1.8.10-rc"
    network_mode: "host"
    env_file:
      - suricata/.env
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - varlib_suricata:/var/lib/suricata/rules
      - data:/data
      - varlib_box4s:/var/lib/box4s/
    user: "0:44269"
  metricbeat:
    build: metricbeat/.
    container_name: metricbeat
    image: "registry.gitlab.com/4sconsult/box4s/metricbeat:1.8.10-rc"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    user: "0:44269"
  heartbeat:
    build: heartbeat/.
    container_name: heartbeat
    image: "registry.gitlab.com/4sconsult/box4s/heartbeat:1.8.10-rc"
    depends_on:
      elasticsearch:
        condition: service_healthy
  logstash:
    build: logstash/.
    container_name: logstash
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file:
     - /etc/default/logstash
     - ../config/secrets/db.conf
     - logstash/.env.ls
    ports:
      - 9600:9600
      - 5044:5044
      - 5046:5046
    image: "registry.gitlab.com/4sconsult/box4s/logstash:1.8.10-rc"
    volumes:
      - varlib_logstash:/var/lib/logstash/
      - etcbox4s_logstash:/etc/logstash/conf.d/general/
      - varlib_box4s:/var/lib/box4s/
    user: "0:44269"
  filebeat:
    build: filebeat/.
    container_name: filebeat
    depends_on:
        elasticsearch:
            condition: service_healthy
    image: "registry.gitlab.com/4sconsult/box4s/filebeat:1.8.10-rc"
    volumes:
      - varlib_logstash:/var/lib/logstash/
      - data:/data
    user: root:44269
  web:
    container_name: web
    networks:
      default:
        ipv4_address: 172.20.08.11
    image: "registry.gitlab.com/4sconsult/box4s/web:1.8.10-rc"
    build: web/.
    command: >
     bash -c "python main.py db upgrade head &&
     gunicorn --bind 0.0.0.0:5000 main:app"
    volumes:
       - static_volume:/home/app/web/source/static
       - /var/log/box4s/:/var/log/box4s/
       - varlib_box4s/:/var/lib/box4s/
       - varlib_elastalert_rules:/var/lib/elastalert/rules/
       - /etc/box4s/smtp.conf:/etc/box4s/smtp.conf
       - /etc/box4s/modules.conf:/etc/box4s/modules.conf
       - /etc/msmtprc:/etc/box4s/msmtprc
       - /etc/ssl/certs/BOX4s-SMTP.pem:/etc/ssl/certs/BOX4s-SMTP.pem
       - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
       - /etc/environment:/etc/environment
       - /etc/box4s/logstash/BOX4s-special.conf:/etc/box4s/logstash/BOX4s-special.conf
       - /etc/default/logstash:/etc/default/logstash
       - /etc/netplan:/etc/_netplan/
       - /etc/nginx/certs/:/etc/nginx/certs/
    expose:
      - 5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/_health"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Add dockerhost IP to /etc/hosts in container for ssh
    extra_hosts:
      - "dockerhost:${INT_IP}"
    env_file:
      - web/web.env
      - ../config/secrets/web.conf
      - /etc/box4s/smtp.conf
      - /etc/box4s/modules.conf
      - ../VERSION
    environment:
      - KUNDE
    depends_on:
      db:
        condition: service_healthy
    user: "app:44269"
  db:
    container_name: db
    image: "registry.gitlab.com/4sconsult/box4s/db:1.8.10-rc"
    build: db/.
    volumes:
      - varlib_postgresql/:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ../config/secrets/db.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: "0:44269"
  nginx:
    container_name: nginx
    image: "registry.gitlab.com/4sconsult/box4s/nginx:1.8.10-rc"
    build: nginx/.
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/source/static
      # certs (placed in host /etc/ folder by install script)
      - /etc/nginx/certs:/etc/nginx/certs
    depends_on:
      - web
      - kibana
      - wiki
    user: "0:44269"
  dnsmasq:
    container_name: dnsmasq
    image: "registry.gitlab.com/4sconsult/box4s/dnsmasq:1.8.10-rc"
    build: dnsmasq/.
    ports:
      - 53:5353/tcp
      - 53:5353/udp
    volumes:
      - varlib_box4s:/var/lib/box4s/
    user: "dnsmasq:44269"
  elastalert:
    container_name: elastalert
    image: "registry.gitlab.com/4sconsult/box4s/elastalert:1.8.10-rc"
    depends_on:
      elasticsearch:
        condition: service_healthy
    build: elastalert/.
    restart: always
    volumes:
      - varlib_elastalert_rules:/opt/elastalert/rules
      - /var/lib/box4s/elastalert_smtp.yaml:/opt/elastalert/smtp_auth_file.yaml
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    expose:
      - 3030
      - 3333
    user: "0:44269"
  core4s:
    container_name: core4s
    build: core4s/.
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /data/suricata/eve.json:/core4s/workfolder/suricata/eve.json
      - /var/lib/box4s:/core4s/workfolder/var/lib/box4s
      - varlib_logstash:/core4s/workfolder/var/lib/logstash
      - /home/amadmin/box4s/docker/web/source/wazuh:/core4s/workfolder/wazuh_files
      - /home/amadmin/box4s/config/secrets:/core4s/config/secrets:ro
    image: "registry.gitlab.com/4sconsult/box4s/core4s:1.8.10-rc"
  wiki:
    container_name: wiki
    image: "registry.gitlab.com/4sconsult/box4s/wiki:1.8.10-rc"
    build: wiki/.
    restart: always
    volumes:
      - varlib_docs:/wiki/
    expose:
      - 80
    user: "0:44269"
networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.08.0/24
volumes:
  # to persist data beyond container's life
  spiderfoot_data:
  gvm-data:
    external: true
  static_volume:
  data:
    external: true
  varlib_suricata:
    external: true
  varlib_postgresql:
    external: true
  varlib_box4s:
    external: true
  varlib_logstash:
    external: true
  varlib_docs:
    external: true
  varlib_elastalert_rules:
    external: true
  etcbox4s_logstash:
    external: true
