version: '2.3'

services:
  elasticsearch:
    build: elasticsearch/.
    container_name: elasticsearch
    restart: always
    ports:
     - 9200:9200
    image: "docker-registry.am-gmbh.de/it-security/b4s/elasticsearch:dev"
    volumes:
     - data:/data
  kibana:
    build: kibana/.
    container_name: kibana
    restart: always
    ports:
     - 5601:5601
    image: "docker-registry.am-gmbh.de/it-security/b4s/kibana:dev"
    #depends_on:
    #  elasticsearch:
    #    condition: service_started
    stop_signal: SIGKILL
  web:
    image: "docker-registry.am-gmbh.de/it-security/b4s/web:dev"
    build:
      context: ./web
    container_name: web
    volumes:
      - ./web/:/usr/src/app/
      - ./web/update.log:/var/log/box4s/update.log
      - ./web/.update.state:/var/lib/box4s/.update.state
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/_health"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env.dev.web
      - ../VERSION
    depends_on:
      - db
  db:
    image: "docker-registry.am-gmbh.de/it-security/b4s/db:dev"
    build:
      context: ./db
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=zgJnwauCAsHrR6JB
      - POSTGRES_DB=box4S_db

volumes:
  # to persist data beyond container's life
  postgres_data:
  data:
