version: '2.3'

services:
  elasticsearch:
    build: elasticsearch/.
    container_name: elasticsearch
    restart: always
    ports:
     - 9200:9200
    image: "docker-registry.am-gmbh.de/it-security/b4s/elasticsearch:dev"
    volumes:
     - data:/data
  kibana:
    build: kibana/.
    container_name: kibana
    restart: always
    ports:
     - 5601:5601
    image: "docker-registry.am-gmbh.de/it-security/b4s/kibana:dev"
    #depends_on:
    #  elasticsearch:
    #    condition: service_started
    stop_signal: SIGKILL
  web:
    build:
      context: ./web
    command: python main.py run -h 0.0.0.0
    volumes:
      - ./web/:/usr/src/app/
      - ./web/update.log:/var/log/box4s/update.log
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev.web
      - ../VERSION
    depends_on:
      - db
  db:
    build:
      context: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=zgJnwauCAsHrR6JB
      - POSTGRES_DB=box4S_db

volumes:
  # to persist data beyond container's life
  postgres_data:
  data:
