#server.port: 5601
server.host: "0.0.0.0"
#path.data needs to be commented out for 7.9.0
#path.data: "/var/lib/kibana"
server.basePath: "/kibana"
server.rewriteBasePath: true
server.name: "box4security"
elasticsearch.hosts: "http://elasticsearch:9200"
xpack.canvas.enabled: false
#Canvas disabled for now since it crashes kibana with wazuh enabled
kibana.index: ".kibana"
#server.ssl.enabled: True
logging.dest: /var/log/kibana/kibana.log
logging.silent: false
logging.quiet: false
logging.verbose: false
telemetry.enabled: false
