es_host: localhost
es_port: 9200
name: Example_rule
type: frequency
index: suricata-*

num_events: 1
timeframe:
    minutes: 5
filter:
- term:
    alert.signature.keyword: "SURICATA STREAM FIN invalid ack"
alert:
- command:
        #command: "echo \" TEST\" >>  /home/amadmin/elastalert.txt"
        #command: "echo \"Testmail elastalert  Alarm aufgetrete bei ","${COMPANY_NAME}"," am:","{@timestamp}\""," | mail -s","\"Alarmsignatur\""," box@4sconsult.de"]
        #command: ["echo","\"Testmail elastalert  Alarm aufgetrete bei"," am:","@{timestamp}\""," | mail -s","\"Alarmsignatur:","{event[host]}","\""," box@4sconsult.de"]
        command: "echo \"Testmail elastalert  Alarm aufgetrete bei {event[host]} am: @{timestamp}\" | mail -s \"Alarmsignatur: {alert[signature]} \"  box@4sconsult.de"

        # #command: ["/bin/echo ", "{match[rule_name]}","{match[@timestamp]}","{match[matches]}", "| mail -s","Alarm von ","{match[host.name]}","dominik.foert@am-gmbh.d
