################### Heartbeat Configuration Example #########################
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/heartbeat/index.html
############################# Heartbeat ######################################
# Configure monitors
heartbeat.config.monitors:
  path: /etc/heartbeat/monitors.d/*.yml
  reload.enabled: true
  reload.period: 10s
  #==================== Elasticsearch template setting ==========================
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  #_source.enabled: false
#================================ General =====================================
#============================== Dashboards =====================================
#============================== Kibana =====================================
#============================= Elastic Cloud ==================================
#================================ Outputs =====================================
#-------------------------- Elasticsearch output ------------------------------
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash:5044"]
#================================ Logging =====================================
# Available log levels are: error, warning, info, debug
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/heartbeat
  name: heartbeat
  keepfiles: 7
  permissions: 0644
#============================== Xpack Monitoring ===============================
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch:
        hosts: ["elasticsearch:9200"]
