import os
POSTGRESQL_DB = 'box4S_db'
POSTGRESQL_USER = os.getenv(POSTGRES_USER)
POSTGRESQL_PASS = os.getenv(POSTGRES_PASSWORD)
POSTGRESQL_HOST = os.getenv(POSTGRES_HOST)
POSTGRESQL_PORT = os.getenv(POSTGRES_PORT)
SQL_VERBOSE = False
