import os
POSTGRESQL_DB = 'box4S_db'
POSTGRESQL_USER = os.getenv(POSTGRES_USER)
POSTGRESQL_PASS = os.getenv(POSTGRES_PASSWORD)
POSTGRESQL_HOST = 'localhost'
POSTGRESQL_PORT = 5432
SQL_VERBOSE = False
