version: '3.7'

services:
  web:
    build:
      context: ./docker/web
      network: host
    command: python main.py run -h 0.0.0.0
    volumes:
      - ./docker/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    build:
      context: ./docker/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=zgJnwauCAsHrR6JB
      - POSTGRES_DB=box4S_db

volumes:
  # to persist data beyond container's life
  postgres_data:
