version: '3.7'

services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile.prod
      network: host
    command: gunicorn --bind 0.0.0.0:5000 main:app
    volumes:
       - static_volume:/home/app/web/source/static
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    build:
      context: ./docker/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - 8080:80
    volumes:
      - static_volume:/home/app/web/source/static
    depends_on:
      - web

volumes:
  # to persist data beyond container's life
  postgres_data:
  static_volume:
